### ISSUE TITLE
online demo please :)

### ISSUE THREAD

**Issue by winkler1** [seatgeek/react-slider#5]
even rawgit would be fine...

**Comment by garetht** [comment]
I'll put up one soon, but for now you can see the use of our filter in production on a page such as this (https://seatgeek.com/spurs-at-pelicans-tickets/4-15-2015-new-orleans-louisiana-smoothie-king-center/nba/2284994/) - it'll work until April 15 this month. Click on 'Show Price Filter' in the box to the left: 

![](http://cl.ly/image/37201u221P22/Screen%20Shot%202015-01-09%20at%2010.42.27%20AM.png)

**Comment by winkler1** [comment]
cool, thanks

**Comment by josegonzalez** [comment]
For reference, an online demo can be seen on any of the https://seatgeek.com event pages.
