### ISSUE TITLE
Is this published on npm/bower?

### ISSUE THREAD

**Issue by winkler1** [seatgeek/react-slider#6]
Can't tell. Also, seems like there's an npm module by that name already.... https://github.com/mpowaga/react-slider

**Comment by gpbl** [comment]
:+1: for a npm module

**Comment by garetht** [comment]
It's [published on Bower](https://github.com/seatgeek/react-slider/blob/master/bower.json)! Will probably have to wrap it a bit more for NPM - planning to do that soon.

**Comment by gpbl** [comment]
I see... No experience with bower, but how does it play with build systems? 

With the current implementation I need to copy/paste the source and add the require manually. I am using webpack but I guess browserify users would run in the same issue.

**Comment by gpbl** [comment]
BTW a possible package name could be `react-slider-component` :-)

**Comment by garetht** [comment]
Bower works really well with build systems. We use `gulp` ourselves, and our current implementation uses [`bower-files`](https://www.npmjs.com/package/bower-files) to get lists of filepaths that we feed into the `gulp` pipeline, but `bower-files` itself is asset pipeline-agnostic, I believe.

Sounds like a good name, I'll keep that in mind!

**Comment by kraf** [comment]
:+1: for npm module

**Comment by josegonzalez** [comment]
If someone would like to add instructions for publishing this to NPM - with accompanying PR for any changes - I'd be happy to do so. For the moment, we're only publishing it through bower as that is how we install react-slider.
