### ISSUE TITLE
Idea for styling

### ISSUE THREAD

**Issue by gpbl** [seatgeek/react-slider#7]
Hi, cool slider! 

I need to get a bit the CSS... for that, I'd love to have class names not polluting the CSS name space, i.e. using BEM like syntax: `.slider`, `.slider__bar`, `.slider__left` etc. (or if you don't like `__`, we can use `.slider-bar`).

Also, looking to the code, it doesn't seem difficult to switch to relative widths (i.e. relative to the container).

What do you think?

**Comment by garetht** [comment]
Sounds good! This was written before we tried to switch to BEM, and moving it towards BEM will be in line with our goals.

**Comment by josegonzalez** [comment]
@gpbl If you have a PR for this, we'd love to see it. Closing this otherwise as there isn't anything actionable here.
