### ISSUE TITLE
State is tightly coupled with CSS class names

### ISSUE THREAD

**Issue by vcarl** [seatgeek/react-slider#9]
I spent a bit of time trying to get this to work for my use case, but everything is so tightly coupled that it's very difficult to comprehend what influences what. 

```javascript
    targetClassName = e.target.className,
    direction = targetClassName.match(/(\w+)Number/)[1],
    otherDirection = this.getOtherDirection(direction),
// [...]
    var otherNumber = otherDirection + "Number";
    stateObject[otherNumber] = this.state[otherNumber];
```

The above only works if the events are triggered by DOM elements with the right class, and wouldn't have passed code review where I work.

**Comment by garetht** [comment]
That is indeed terrible code.

**Comment by josegonzalez** [comment]
@vcarl Would you be interested in providing a PR to unsuss the CSS class names?

**Comment by vcarl** [comment]
I started to, but it would really be a fundamental rewrite. And I disagree with a lot of the prop names, so it'd be a completely different component if I made the changes I felt necessary for me to use it in my code. I'm going with [mpowaga/react-slider](https://github.com/mpowaga/react-slider) instead because I really just need a functional slider to implement a feature at work.

**Comment by josegonzalez** [comment]
Alright then, closing this. Feel free to revisit in the future if you have time.
